#!/usr/bin/env bash
set -e
dapp build

function has() { command -v "$1" >/dev/null 2>&1; }
has ethrun || has hsevm || {
  echo >&2 "Either `ethrun' or `hsevm' need to be present for running tests"
  exit 1
}

if has ethrun; then
  # compute library addresses as hash(sender, nonce)
  sender="0x00a329c0648769a73afac7f9381e08fb43dbea72"  # ethrun sender
  nonce=1048576  # magic starting nonce

  # need to know the names and locations of all of the libraries
  sources=$(find $DAPP_SRC $DAPP_LIB -name '*.sol')
  libraries=$(grep -EH '^library\s+\w+' $sources \
            | sed -E 's/:library[[:blank:]]+([_[:alnum:]]+)[[:blank:]]+(\{|is).*/:\1/' \
            | sort)
  links=""
  for lib in $libraries; do
      address="$(dapp address $sender $nonce)"
      links="$links $lib:$address"
      ((nonce++))
  done
  (set -x; solc --link --libraries "$links" $DAPP_OUT/*.bin)

  # pass the library bin files through to ethrun
  # (needs to be exact same order as above for nonces)
  deploy=$(echo "$libraries" | sed -E "s/.*:(.*)/$DAPP_OUT\/\1.bin/")
  (set -x; dapp quicktest "$@" "$DAPP_OUT" $deploy)
fi

if has hsevm; then
  for x in $DAPP_OUT/*.t.sol.json; do
    (set -x; hsevm dapp-test --json-file "$x" --dapp-root .)
  done
fi
